
-- Schéma

DROP SCHEMA IF EXISTS exemple CASCADE;
CREATE SCHEMA exemple;


-- Tables

CREATE TABLE compte (
	idcompte		INT				GENERATED BY DEFAULT AS IDENTITY,
	pseudo			VARCHAR(25)		NOT NULL,
	motdepasse		VARCHAR(25) 	NOT NULL,
	email			VARCHAR(100)	NOT NULL,
	UNIQUE (pseudo),
	PRIMARY KEY (idcompte)
);

CREATE TABLE role (
	idcompte		INT				NOT NULL,
	role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (idcompte) REFERENCES compte (idcompte) ON DELETE CASCADE,
	PRIMARY KEY (idcompte, role)
);

CREATE TABLE categorie (
	idcategorie		INT				GENERATED BY DEFAULT AS IDENTITY,
	libelle			VARCHAR(25)		NOT NULL,
	debut			DATE,
	PRIMARY KEY (idcategorie)
);

CREATE TABLE personne (
	idpersonne		INT				GENERATED BY DEFAULT AS IDENTITY,
	idcategorie		INT				NOT NULL,
	nom				VARCHAR(25)  	NOT NULL,
	prenom			VARCHAR(25) 	NOT NULL,
	FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie),
	PRIMARY KEY (idpersonne)
);

CREATE TABLE telephone (
	idtelephone		INT				GENERATED BY DEFAULT AS IDENTITY,
	idpersonne		INT			 	NOT NULL,
	Libelle			VARCHAR(25)		NOT NULL,
	Numero			VARCHAR(25)		NOT NULL,
	FOREIGN KEY (idpersonne) REFERENCES personne (idpersonne) ON DELETE CASCADE,
	PRIMARY KEY (idtelephone)
);

CREATE TABLE memo (
	idmemo			INT				GENERATED BY DEFAULT AS IDENTITY,
	titre			VARCHAR(50)		NOT NULL,
	description		VARCHAR(1000),
	flagurgent		BOOLEAN			NOT NULL,
	idcategorie		INT,
	statut			CHAR(1)	 		NOT NULL	CHECK ( statut IN ( 'A', 'E', 'F' ) ),
	effectif		INT,
	budget			NUMERIC( 12, 2 ),
	echeance		DATE,
	heure			TIME,
	FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie),
	PRIMARY KEY (idmemo)
);

CREATE TABLE abonner (
	idmemo		INT	NOT NULL,
	idCompte	INT	NOT NULL,
	FOREIGN KEY (idmemo) REFERENCES memo (idmemo) ON DELETE CASCADE,
	FOREIGN KEY (idCompte) REFERENCES compte (idCompte) ON DELETE CASCADE,
	PRIMARY KEY (idmemo, idCompte)
);

CREATE TABLE agir (
	idmemo		INT	NOT NULL,
	idpersonne	INT	NOT NULL,
	fonction	VARCHAR(100),
	debut		DATE,
	FOREIGN KEY (idmemo) REFERENCES memo (idmemo) ON DELETE CASCADE,
	FOREIGN KEY (idpersonne) REFERENCES personne (idpersonne)ON DELETE CASCADE,
	PRIMARY KEY (idmemo, idpersonne)
);

CREATE TABLE service (	
	idservice 		INT				GENERATED BY DEFAULT AS IDENTITY, 
	nom 			VARCHAR(50)		NOT NULL, 
	anneecreation	SMALLINT,
	flagsiege		BOOLEAN			NOT NULL, 
	idpersonne		INT,
	FOREIGN KEY (idpersonne) REFERENCES personne (idpersonne),
	PRIMARY KEY (idservice)
);

